apiVersion: v1
kind: Pod
metadata:
  name: pod-pvc-sc
  labels:
    app: pod-pvc-sc
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /external-data-pv
          name: primeiro-pv
  volumes:
    - name: primeiro-pv
      persistentVolumeClaim:
        claimName: pvc-sc-1